# Generated by Django 4.2.1 on 2023-06-03 09:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='EG'),
        ),
    ]
