# Generated by Django 4.2.1 on 2023-05-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('descreption', models.TextField(max_length=1000)),
                ('published_at', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=1, max_digits=10)),
                ('category', models.TextField(max_length=100)),
            ],
        ),
    ]
