# Generated by Django 4.2.1 on 2023-05-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='title',
            new_name='job',
        ),
    ]
