# Generated by Django 4.2.1 on 2023-05-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='descreption',
            new_name='description',
        ),
    ]
